version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fastwalletsystem-dev-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: fastwalletsystem
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d fastwalletsystem']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fastwalletsystem-dev-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    container_name: fastwalletsystem-test-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: fastwalletsystem_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d fastwalletsystem_test']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fastwalletsystem-dev-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@fastwalletsystem.com
      PGADMIN_DEFAULT_PASSWORD: dev123
    ports:
      - '8080:80'
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_dev_data:
  postgres_test_data:
  pgadmin_dev_data:
  redis_dev_data:
